apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-grafana
spec:
  parallelism: 1
  script:
    configMap:
      name: test-scripts
      # TODO - Want a different test script? Change it here.
      file: simple.js
  arguments:  --tag testid=k6-output-simple
  runner:
    # TODO Change the image to your published image!
    image: adityamodak/prom-k6-operator:latest
    env:
      - name: K6_OUT
        value: experimental-prometheus-rw
    envFrom:
     - configMapRef:
         name: prometheus-config
    
